config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    get '', to: :index
    put '', to: :update
  end

  get 'home/index'
  root 'home#index'
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role
  before_create :set_default_role

  private
  def set_default_role
    self.role ||= Role.find_by_name('user')
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/_alerts.html.haml
- if params[:success] != nil
  .ui.positive.message
    .header
      Yaaaay!
    %ul.list
      %li= params[:success] == nil ? success : params[:success]
- if params[:alert] != nil
  .ui.negative.message
    .header
      Oooops! Warning ?
    %ul.list
      %li= params[:alert] == nil ? alert : params[:alert]

app/views/admin/_navbar.html.haml
.ui.top.attached.menu
  = link_to root_path, :class => "item" do
    = image_tag('http://zizaza.com/cache/big_thumb/iconset/581946/581948/PNG/256/like_a_flat/book_web_book_png_book_icon_flat_icon_png.png')
  - if current_user != nil
    - if current_page?(admin_path)
      = link_to('Домівка', admin_path, :class => "active item")
    - else
      = link_to('Домівка', admin_path, :class => "item")
    .right.menu
      -# .item
      -#   .ui.tiny.horizontal.statistic
      -#     .value= Upload.all.count
      -#     .label Книг
      -# - if current_user.role != nil
      -#   .item
      -#     - if current_user.role.name == 'admin'
      -#       .ui.green.label= current_user.role.name
      -#     - elsif current_user.role.name == 'moderator'
      -#       .ui.orange.label= current_user.role.name
      -#     - else
      -#       .ui.blue.label= current_user.role.name
      -# - if current_page?(admin_settings_path)
      -#   = link_to('Налаштування', admin_settings_path, :class => "ui right aligned active item")
      -# - else
      -#   = link_to('Налаштування', admin_settings_path, :class => "ui right aligned item")
      = link_to('Вийти', destroy_user_session_path, :method => :delete, :class => "ui right aligned item")
  - else
    .right.menu
      = link_to('Увійти', new_user_session_path, :class => "ui right aligned item")

app/views/admin/index.html.haml
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/home/index.html.haml
= render partial: 'admin/navbar'
.ui.container{ :style => "margin-top: 80px;" }
  = render partial: 'admin/alerts'
  .ui.header{style: "padding-top:250px;font-size:20px;font-weight:300;width:500px;margin: 0 auto;text-align: justify;"}
    %p{style: "text-align: center;"}
      Вітаємо у онлайн бібліотеці ЛНУ
    %p
      Адміністрація вебсайту не несе відповідальності за контент розміщений на сайті. Все, що розміщено на даному сайті, захищено законом про вільне володіння доступною інформацією. База даних заснована на політиці вільного відвантаження інформативних матералів.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title LNU Attractions
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield